server:
  port: 8083
spring:
  application:
    name: course-service
  datasource:
    url: jdbc:postgresql://localhost:5432/course_db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
config:
  import: configserver:http://localhost:8888


#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
#  instance:
#    prefer-ip-address: true
